In [2]:
import numpy as np

# Input data
x = np.array([[0,0,1], 
             [0,1,1],
             [1,0,1],
             [1,1,1]])

y = np.array([[0],
             [1],
             [1],
             [0]])

In [3]:
print(x)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]]


In [4]:
print(y)

[[0]
 [1]
 [1]
 [0]]


In [5]:
# Build the model
num_epochs = 60000

# Initialize the weights in range [-1:1]
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

In [6]:
print(syn0)

[[ 0.63990834 -0.18948874  0.5919501   0.7796155 ]
 [-0.05476144 -0.90641784 -0.03868696  0.42041879]
 [ 0.36586295  0.38881293 -0.95634443  0.19341471]]


In [7]:
print(syn1)

[[-0.41537545]
 [ 0.410286  ]
 [-0.43709096]
 [ 0.49657617]]


In [9]:
def nonlin(x, derivate=False):
    if (derivate == True):
        return x*(1-x)
    else:
        return 1/(1+np.exp(-x))

In [12]:
# Training
for i in range(num_epochs):
    # Feed forward to input layer
    input_layer = x
    hidden_layer = nonlin(np.dot(input_layer, syn0))
    output_layer = nonlin(np.dot(hidden_layer, syn1))
    
    # Backpropagation
    output_error = y - output_layer
    output_delta = output_error*nonlin(ouput_layer, derivate=True)
    
    hidden_error = np.dot(output_delta, syn1.T)
    hidden_delta = hidden_error*nonlin(hidden_layer, derivate=True)
    
    # How much did we miss the target
    if (i%10000)==0:
        print("Error", str(np.mean(np.abs(output_error))))
    
    # Update the weight
    syn1 += np.dot(hidden_layer.T, output_delta)
    syn0 += np.dot(input_layer.T, hidden_delta)
    

Error 0.49927608605
Error 0.000499680233264
Error 0.000231853614877
Error 0.000149942253272
Error 0.000110528381435
Error 8.74165938282e-05
