## 1. Save TensorFlow Variables

In [1]:
import tensorflow as tf

# The path to save the data
save_file = "./model.ckpt"

# Tensor weights and bias
weights = tf.Variable(tf.truncated_normal([2,3]))
bias = tf.Variable(tf.truncated_normal([3]))

# Class to save and restore tensor
saver = tf.train.Saver()

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    print("Weights:")
    print(sess.run(weights))
    print("Bias: \n")
    print(sess.run(bias))
    
    # Save the model
    saver.save(sess, save_file)

Weights:
[[ 0.56385857 -0.62494588 -0.06487752]
 [-0.54834282  1.11871111 -1.24532354]]
Bias: 

[ 1.15863836 -1.6544224   0.09405582]


## 2.Load Tensor Variable back into new model

> Dont nedd to call the ***sess.run(tf.global_variables_initializer())***

In [2]:
# Remove the previous variables
tf.reset_default_graph()

# Create new weight and bias
weights = tf.Variable(tf.truncated_normal([2,3]))
bias = tf.Variable(tf.truncated_normal([3]))

# Class to save or restore tensor variable
saver = tf.train.Saver()

with tf.Session() as sess:
    # Load the weights and bias run in the save_file
    saver.restore(sess, save_file)
    
    print("Weights: ")
    print(sess.run(weights))
    print("Bias: \n") 
    print(sess.run(bias))

Weights: 
[[ 0.56385857 -0.62494588 -0.06487752]
 [-0.54834282  1.11871111 -1.24532354]]
Bias: 

[ 1.15863836 -1.6544224   0.09405582]
